In [ ]:
# it is good to know central tendency for variable that im going to work with

In [21]:
import numpy as np
from statistics import mean
from scipy import stats

In [10]:
arr = np.random.randint(low=1, high=56, size=(23))
arr

array([15, 18, 35, 12, 47, 41, 47, 47, 23, 45, 50, 18, 49, 11,  1, 13, 45,
       13, 53, 10,  6, 35, 21])

In [16]:
sum(arr)/len(arr)

np.float64(28.47826086956522)

In [ ]:
# here is how i can find mean, first two is from numpy, third is statistics library
arr.mean(), np.mean(arr), mean(arr)

(np.float64(28.47826086956522), np.float64(28.47826086956522), np.int64(28))

In [18]:
# but mean is sensitive to outliers
arr2 = np.insert(arr, 1, 2564)
arr2

array([  15, 2564,   18,   35,   12,   47,   41,   47,   47,   23,   45,
         50,   18,   49,   11,    1,   13,   45,   13,   53,   10,    6,
         35,   21])

In [ ]:
# here i can clearly see that mean value is much higher then the real distribution is
arr2.mean()

np.float64(134.125)

In [ ]:
# one way to deal with it is to find trimmed mean using stats module from scipy library
# it will cut some min and max values from sample
stats.trim_mean(arr2, proportiontocut=0.2)
# so after cutting 20% of values from sample im getting much closer to the real mean value

np.float64(29.6875)

In [50]:
# other oprtion is ti find weighted mean
# it will multiply values by weights and divide by weights sum
# weights can be added by significanse of the values. So i can add less weights to outliers

weights = [] 

for el in arr2:
    if el < 60 and el > 45:
        weights.append(0.6)
    elif el < 30:
        weights.append(0.4)
    else:
        weights.append(0.1)

weights = np.array(weights)
weights

# weights sample must be same size as main sample

array([0.4, 0.1, 0.4, 0.1, 0.4, 0.6, 0.1, 0.6, 0.6, 0.4, 0.1, 0.6, 0.4,
       0.6, 0.4, 0.4, 0.4, 0.1, 0.4, 0.6, 0.4, 0.4, 0.1, 0.4])

In [51]:
# for finding weighted mean i will need to use np.dot()
arr2.dot(weights)
# or
np.dot(arr2, weights)

np.float64(516.7)

In [52]:
# so the weighted mean equasion will look like this
arr2.dot(weights)/sum(weights)

np.float64(57.411111111111104)

In [53]:
# also for weighted mean i can use this 
np.average(arr2, weights=weights)

np.float64(57.41111111111112)