In [ ]:
# it is good to know central tendency for variable that im going to work with

In [70]:
import numpy as np
from statistics import mean
from scipy import stats
import pandas as pd

In [10]:
arr = np.random.randint(low=1, high=56, size=(23))
arr

array([15, 18, 35, 12, 47, 41, 47, 47, 23, 45, 50, 18, 49, 11,  1, 13, 45,
       13, 53, 10,  6, 35, 21])

In [16]:
sum(arr)/len(arr)

np.float64(28.47826086956522)

In [ ]:
# here is how i can find mean, first two is from numpy, third is statistics library
arr.mean(), np.mean(arr), mean(arr)

(np.float64(28.47826086956522), np.float64(28.47826086956522), np.int64(28))

In [18]:
# but mean is sensitive to outliers
arr2 = np.insert(arr, 1, 2564)
arr2

array([  15, 2564,   18,   35,   12,   47,   41,   47,   47,   23,   45,
         50,   18,   49,   11,    1,   13,   45,   13,   53,   10,    6,
         35,   21])

In [ ]:
# here i can clearly see that mean value is much higher then the real distribution is
arr2.mean()

np.float64(134.125)

In [ ]:
# one way to deal with it is to find trimmed mean using stats module from scipy library
# it will cut some min and max values from sample
stats.trim_mean(arr2, proportiontocut=0.2)
# so after cutting 20% of values from sample im getting much closer to the real mean value

np.float64(29.6875)

In [ ]:
# other option is to find weighted mean
# it will multiply values by weights and divide by weights sum
# weights can be added by significanse of the values. So i can add less weights to outliers

weights = [] 

for el in arr2:
    if el < 60 and el > 45:
        weights.append(0.6)
    elif el < 30:
        weights.append(0.4)
    else:
        weights.append(0.1)

weights = np.array(weights)
weights

# weights sample must be same size as main sample

# weighted mean is often used in physics and economica

array([0.4, 0.1, 0.4, 0.1, 0.4, 0.6, 0.1, 0.6, 0.6, 0.4, 0.1, 0.6, 0.4,
       0.6, 0.4, 0.4, 0.4, 0.1, 0.4, 0.6, 0.4, 0.4, 0.1, 0.4])

In [51]:
# for finding weighted mean i will need to use np.dot()
arr2.dot(weights)
# or
np.dot(arr2, weights)

np.float64(516.7)

In [52]:
# so the weighted mean equasion will look like this
arr2.dot(weights)/sum(weights)

np.float64(57.411111111111104)

In [53]:
# also for weighted mean i can use this 
np.average(arr2, weights=weights)

np.float64(57.41111111111112)

In [ ]:
# also i can use median, because it is good for samples with ouliers too
np.median(arr2)

np.float64(29.0)

In [61]:
# i can use mode also, it returns the value and how many times it is presented in sample
stats.mode(arr2)

ModeResult(mode=np.int64(47), count=np.int64(3))

In [ ]:
# mode is more used with categorical or binary [0, 1] data
bind = [1, 0, 1, 1, 1, 0]

stats.mode(bind)

ModeResult(mode=np.int64(1), count=np.int64(4))

In [71]:
df = pd.read_csv('data_d.txt')

In [73]:
df.head()

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520   
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520   
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045   
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335   
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335   

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky   
1      Claire Gute   Consumer  United States        Henderson    Kentucky   
2  Darrin Van Huff  Corporate  United States      Los Angeles  California   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida   

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases   
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs   
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels   
3      33311.0  South  FUR-TA-10000577        Furniture       Tables   
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  
0                  Bush Somerset Collection Bookcase  261.9600  
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400  
2  Self-Adhesive Address Labels for Typewriters b...   14.6200  
3      Bretford CR4500 Series Slim Rectangular Table  957.5775  
4                     Eldon Fold 'N Roll Cart System   22.3680

In [84]:
df['Sales'].mean()

np.float64(230.76905945918367)

In [85]:
df['Sales'].median()

np.float64(54.489999999999995)

In [88]:
len(df['Sales'])

9800

In [ ]:
# to find best proportion to cut for trimmed mean i can use this 
len(df['Sales']) * 0.1 * 2
# this tells me how many values will be trimmed
# for df this size this looks a little bit too much

1960.0

In [89]:
len(df['Sales']) * 0.01 * 2

196.0

In [ ]:
# though to find best proportion to cut i need to study data, so median is much safier option
stats.trim_mean(df['Sales'], proportiontocut=0.01)

np.float64(188.935317544773)

In [97]:
# case with mode
val, count = stats.mode(df['Postal Code'])

df[df['Postal Code'] == val].head()

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
110     111  CA-2018-146780  25/12/2018  30/12/2018  Standard Class   
189     190  CA-2016-102281  12/10/2016  14/10/2016     First Class   
190     191  CA-2016-102281  12/10/2016  14/10/2016     First Class   
191     192  CA-2016-102281  12/10/2016  14/10/2016     First Class   
192     193  CA-2016-102281  12/10/2016  14/10/2016     First Class   

    Customer ID  Customer Name      Segment        Country           City  \
110    CV-12805  Cynthia Voltz    Corporate  United States  New York City   
189    MP-17470    Mark Packer  Home Office  United States  New York City   
190    MP-17470    Mark Packer  Home Office  United States  New York City   
191    MP-17470    Mark Packer  Home Office  United States  New York City   
192    MP-17470    Mark Packer  Home Office  United States  New York City   

        State  Postal Code Region       Product ID         Category  \
110  New York      10035.0   East  FUR-FU-10001934        Furniture   
189  New York      10035.0   East  FUR-BO-10002613        Furniture   
190  New York      10035.0   East  TEC-PH-10001552       Technology   
191  New York      10035.0   East  OFF-PA-10000061  Office Supplies   
192  New York      10035.0   East  FUR-BO-10002545        Furniture   

    Sub-Category                                       Product Name    Sales  
110  Furnishings                           Magnifier Swing Arm Lamp   41.960  
189    Bookcases  Atlantic Metals Mobile 4-Shelf Bookcases, Cust...  899.136  
190       Phones  I Need's 3d Hello Kitty Hybrid Silicone Case C...   71.760  
191        Paper                                          Xerox 205   51.840  
192    Bookcases  Atlantic Metals Mobile 3-Shelf Bookcases, Cust...  626.352

In [100]:
# or i can use pandas mode
df['City'].mode()

0    New York City
Name: City, dtype: object