In [2]:
import numpy as np

In [5]:
# one-dimensional array
d1 = np.array([1, 2, 3, 4, 5])
d1

array([1, 2, 3, 4, 5])

In [ ]:
# everything in numpy works with this type
type(d1)

numpy.ndarray

In [7]:
lst = ['a', 'b', 'c']

d11 = np.array(lst)

In [8]:
d11

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
# basic things with arrays
d1.shape # returns number of elements
d1.ndim # shows number of dimensions
d1.dtype # returns type of the array, type of the elements in it

dtype('int64')

In [ ]:
# this way i can set dtype manually
d1 = np.array([1, 2, 3, 4, 5], dtype=np.float64)

In [15]:
# this way i can change dtype of already created array
d1.astype(np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [ ]:
# another way of creating array
lst2 = [1, 2, 3, 4, 5]

np.asarray(lst2) 

array([1, 2, 3, 4, 5])

In [21]:
# summing np.arrays will gave array with results of summing like if was for loop
a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])

a + b 

# this works with all math operations like -, *, /
# when dividing by 0 with numpy it will give 'inf', not an error

array([ 5,  7,  9, 11])

In [22]:
# i can aggregate arrays
a.sum()

np.int64(10)

In [23]:
a.mean()

np.float64(2.5)

In [24]:
a.std()

np.float64(1.118033988749895)