In [39]:
import numpy as np

In [40]:
a = np.asarray([[1, 2, 3], [4, 5, 6]])
b = np.asarray([[4, 2], [5, 8], [1, 0]])

In [41]:
a.shape, b.shape

((2, 3), (3, 2))

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
b

array([[4, 2],
       [5, 8],
       [1, 0]])

In [ ]:
# if i multiplie arrays (matricies)
c = np.dot(a, b)
c
# it does it this way -- 1st row of a * 1st column of b, then 1st row of a * 2nd column of b  
# [(1*4 + 2*5 + 3*1)=17], [(1*2 + 2*2 + 3*0)=18] and so on
# it is called 'dot product'

array([[17, 18],
       [47, 48]])

In [45]:
c.shape

(2, 2)

In [ ]:
# but it is better to use matmul for that
np.matmul(a, b)
# it gives the same result, but algorithm is better suited for that

array([[17, 18],
       [47, 48]])

In [ ]:
# also np.dot() can be used for multiplying by normal numbers
np.dot(a, 4)

array([[ 4,  8, 12],
       [16, 20, 24]])

In [52]:
# np.matmul() works only with matricies
# also np.matmul() can be replaced with @
a @ b

array([[17, 18],
       [47, 48]])

In [56]:
# for multiplying several matricies i can use linalg module from numpy
np.linalg.multi_dot((a, b, a))

array([[ 89, 124, 159],
       [239, 334, 429]])

In [57]:
# also multiplying several matricies can be done by @
a @ b @ a

array([[ 89, 124, 159],
       [239, 334, 429]])

In [58]:
# simple example of dot product
d = np.array([1, 2, 3])
e = np.array([4, 5, 6])

In [ ]:
# does the same as np.dot(), but for 1d arrays?
np.inner(d, e)

np.int64(32)

In [64]:
# check
de = 1*4 + 2*5 + 3*6
de

32

In [74]:
# i can also perform cartesian product
# it is like finding all possible combinations
np.outer(d, e)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [ ]:
# this is how it works
cartesian_product = np.array([[1*4, 1*5, 1*6], [2*4, 2*5, 2*6], [3*4, 3*5, 3*6]])
cartesian_product

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [76]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# trace of a matrix - its a sum of all elements of the main diagonal
np.trace(a)
# so for arrray 'a' main diagonal is 1, 5 and sum is 6

np.int64(6)

In [84]:
# also there is one characteristic of a matrix - determinant (det)
# depending on values in the matrix it changes and describes it 
# the matrix should be square 
e = np.array([[2, 2, 2], [1, 1, 1], [4, 4, 4]])
np.linalg.det(e)


np.float64(0.0)

In [ ]:
# this thing helps to find eig values from corr coef matrix
# this values does the greatest impact on the subject, in another words have biggest corr coef in matrix
val, vec =  np.linalg.eig(e)
# this function gives two arrays 

In [ ]:
# first is eigen values
val

array([ 7.00000000e+00, -4.47167512e-16,  4.93038066e-32])

In [ ]:
# second is eigen vectors
vec

array([[ 4.36435780e-01,  7.09051139e-01, -1.02512270e-16],
       [ 2.18217890e-01, -7.05146251e-01, -7.07106781e-01],
       [ 8.72871561e-01, -3.90488784e-03,  7.07106781e-01]])