In [2]:
import numpy as np

In [31]:
a = np.array([[1, 2, 3, np.nan], [4, np.inf, 5, -np.inf]])
b = np.array([[1, 2, 3, np.nan, True], [4, np.inf, 5, -np.inf, False]])

In [32]:
# checks if all elements of array are present, or can be interpreted as True
np.all(a)

np.True_

In [33]:
np.all(b)

np.False_

In [35]:
b

array([[  1.,   2.,   3.,  nan,   1.],
       [  4.,  inf,   5., -inf,   0.]])

In [34]:
# also works with axis
np.all(b, axis=1), np.all(b, axis=0)

(array([ True, False]), array([ True,  True,  True,  True, False]))

In [37]:
# np.any() checks are there any elements in array that can be interpreted as true
np.any(b, axis=1)

array([ True,  True])

In [40]:
c = np.array([[1, 2, 3, np.nan, True], [4, np.inf, 5, -np.inf, False], [False, False, 0, False, False]])

In [41]:
np.any(c, axis=1)

array([ True,  True, False])

In [44]:
b

array([[  1.,   2.,   3.,  nan,   1.],
       [  4.,  inf,   5., -inf,   0.]])

In [ ]:
# checks if the elements in array are infinite
np.isfinite(b)

array([[ True,  True,  True, False,  True],
       [ True, False,  True, False,  True]])

In [ ]:
# does the opposite
np.isinf(b)
# notice thet nan is considered neither infinite or finite

array([[False, False, False, False, False],
       [False,  True, False,  True, False]])

In [47]:
# cheks if element is nan
np.isnan(b)

array([[False, False, False,  True, False],
       [False, False, False, False, False]])

In [73]:
# there is a function to check how close are the values in different arrays
d = np.array([0.000005, 0.0003, 0.008])
e = d + 10000
e

array([10000.000005, 10000.0003  , 10000.008   ])

In [82]:
# atol -- absolute tolerance
np.isclose(d, e, atol=9999.9)

array([ True,  True,  True])

In [ ]:
# does the same, returns result for all elements
np.allclose(d, e, atol=9999.9)

True

In [89]:
aa = a.copy()
a.shape, aa.shape

((2, 4), (2, 4))

In [93]:
# compare arrays, must be same shape
aa == a
# or 
np.equal(aa, a)

array([[ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [ ]:
# does the same but for all els at once
# equal_nan=True -- means that nans in arrays are considered equal
np.array_equal(a, aa, equal_nan=True)

True