In [2]:
import numpy as np

In [3]:
arr = [[1, 2, 3, 4], [4, 5, 6, 7]]

a = np.array(arr)
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [4]:
# 2 is for rows and 4 is for columns
a.shape

(2, 4)

In [5]:
a.ndim

2

In [8]:
b = np.array(arr)
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
# each element was summed
# works the same as if it was 1d array
a + b

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14]])

In [ ]:
# with agg its also the same
a.sum()

np.int64(32)

In [ ]:
# in numpy there is axis
# axis = 1 is for columns
# axis = 0 is for rows
# axis = n is if df have more than 2d

In [10]:
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
a.sum(axis=0) # means sum down or vertically

array([ 5,  7,  9, 11])

In [ ]:
a.sum(axis=1) # means sum horizontally

array([10, 22])

In [13]:
arr3 = [
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]]
]

c = np.array(arr3)

In [14]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
c.shape
# 3 inside lists, 2 in each of them, 3 elements in each of 2

(3, 2, 3)

In [16]:
c.ndim

3

In [ ]:
# math operations are the same

In [17]:
# agg operations
c.mean()

np.float64(3.5)

In [18]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
# it is going like deeper/thru the tables
c.mean(axis=0)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
# it is vertically
c.mean(axis=1)

array([[2.5, 3.5, 4.5],
       [2.5, 3.5, 4.5],
       [2.5, 3.5, 4.5]])

In [ ]:
# it is horizontally
c.mean(axis=2)

array([[2., 5.],
       [2., 5.],
       [2., 5.]])