In [2]:
import numpy as np

In [3]:
arr = [[1, 2, 3, 4], [4, 5, 6, 7]]

a = np.array(arr)
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [4]:
# 2 is for rows and 4 is for columns
a.shape

(2, 4)

In [5]:
a.ndim

2

In [6]:
b = np.array(arr)
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [7]:
# each element was summed
# works the same as if it was 1d array
a + b

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14]])

In [8]:
# with agg its also the same
a.sum()

np.int64(32)

In [9]:
# in numpy there is axis
# axis = 1 is for columns
# axis = 0 is for rows
# axis = n is if df have more than 2d

In [10]:
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [11]:
a.sum(axis=0) # means sum down or vertically

array([ 5,  7,  9, 11])

In [12]:
a.sum(axis=1) # means sum horizontally

array([10, 22])

In [13]:
arr3 = [
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]]
]

c = np.array(arr3)

In [14]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [15]:
c.shape
# 3 inside lists, 2 in each of them, 3 elements in each of 2

(3, 2, 3)

In [16]:
c.ndim

3

In [17]:
# math operations are the same

In [18]:
# agg operations
c.mean()

np.float64(3.5)

In [19]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [20]:
# it is going like deeper/thru the tables
c.mean(axis=0)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
# it is vertically
c.mean(axis=1)

array([[2.5, 3.5, 4.5],
       [2.5, 3.5, 4.5],
       [2.5, 3.5, 4.5]])

In [22]:
# it is horizontally
c.mean(axis=2)

array([[2., 5.],
       [2., 5.],
       [2., 5.]])

In [23]:
# with nD arrays i can put multiple axies
c.mean(axis=(0,1))

array([2.5, 3.5, 4.5])

In [ ]:
# this way i can create standart 2d matrix with 1 values on diagonal and all rest are 0
np.eye(10, 10) # first arg is N - number of rows, second is M - number of columns
# M is optional, if not given it defaults to N value

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# this way i can create custom array with 0 or 1 in it
np.zeros(shape=(2, 3, 5)) # in shape i type in what shape for array i want
np.ones(shape=(2, 3, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
# creates new array with the shape of existing one and fills it with 1
np.ones_like(arr)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# does the same, but does not put 0 in array
np.empty(shape=(2, 3, 5))
# use with caution!

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [30]:
# also creates custom array, but lets me fill with desired value
np.full(shape=(2, 3, 5), fill_value=808)

array([[[808, 808, 808, 808, 808],
        [808, 808, 808, 808, 808],
        [808, 808, 808, 808, 808]],

       [[808, 808, 808, 808, 808],
        [808, 808, 808, 808, 808],
        [808, 808, 808, 808, 808]]])

In [35]:
# if i want to make fractional range i cant use range(), since it cant accept float type
# instead i can use numpy
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [ ]:
# in case when i know start and end value and need exact number of values in array i can use this
np.linspace(0, 10, 5) # i need range of 5 values from 0 to 10 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])