In [2]:
import numpy as np

In [5]:
a = [1, 2, 3, 4, 5, 6]
# creates array from random values from collection
np.random.choice(a, size=(3,3,2))

array([[[1, 6],
        [6, 4],
        [6, 3]],

       [[2, 1],
        [6, 4],
        [3, 5]],

       [[3, 5],
        [6, 3],
        [3, 6]]])

In [8]:
# it can also generate from a number. It will generate a range from 0 to this number
np.random.choice(10, (2, 2, 4))

array([[[6, 2, 8, 8],
        [1, 4, 7, 4]],

       [[2, 3, 6, 9],
        [6, 6, 8, 5]]])

In [ ]:
# there is replace argument that determines whether there can be duplicated values
# as a default np.random.choice duplicates values
np.random.choice(10, (2, 2, 2), replace=False)

array([[[5, 8],
        [3, 0]],

       [[1, 2],
        [6, 7]]])

In [29]:
# there is probability argument -- p
p = [0, 0, 0, 0, 0.3 , 0.7]
a, p

([1, 2, 3, 4, 5, 6], [0, 0, 0, 0, 0.3, 0.7])

In [ ]:
# it gives a probability for values to appear in generated array
# p must be the same size as collection and probabilities must sum to 1
np.random.choice(a, (3, 4), p=p)

array([[6, 6, 5, 6],
       [6, 6, 6, 5],
       [6, 5, 6, 6]])