In [2]:
import numpy as np

In [5]:
a = [1, 2, 3, 4, 5, 6]
# creates array from random values from collection
np.random.choice(a, size=(3,3,2))

array([[[1, 6],
        [6, 4],
        [6, 3]],

       [[2, 1],
        [6, 4],
        [3, 5]],

       [[3, 5],
        [6, 3],
        [3, 6]]])

In [8]:
# it can also generate from a number. It will generate a range from 0 to this number
np.random.choice(10, (2, 2, 4))

array([[[6, 2, 8, 8],
        [1, 4, 7, 4]],

       [[2, 3, 6, 9],
        [6, 6, 8, 5]]])

In [ ]:
# there is replace argument that determines whether there can be duplicated values
# as a default np.random.choice duplicates values
np.random.choice(10, (2, 2, 2), replace=False)

array([[[5, 8],
        [3, 0]],

       [[1, 2],
        [6, 7]]])

In [34]:
# there is probability argument -- p
p = [0, 0.3, 0, 0, 0, 0.7]
a, p

([1, 2, 3, 4, 5, 6], [0, 0.3, 0, 0, 0, 0.7])

In [35]:
# it gives a probability for values to appear in generated array
# p must be the same size as collection and probabilities must sum to 1
np.random.choice(a, (3, 4), p=p)

array([[6, 6, 2, 6],
       [6, 2, 6, 6],
       [6, 6, 6, 2]])

In [39]:
b = np.array([1, 2, 3, 4, 5])
# shuffles the given array
np.random.shuffle(b)

In [ ]:
# it does it in place (changes variable)
b

array([5, 3, 4, 1, 2])

In [41]:
# there is a similar functiot that shuffles, but not in place
b = np.array([1, 2, 3, 4, 5])
np.random.permutation(b)

array([3, 2, 1, 5, 4])

In [42]:
# np.random.permutation() can also work like choice if give it only number
np.random.permutation(20) 

array([ 1,  0,  3, 16, 11, 17,  7, 10, 15,  2, 13,  8, 14,  4, 19,  5,  6,
       12, 18,  9])

In [ ]:
# generates random value in range from 0 to 1 
np.random.sample()

0.38001807971678947

In [ ]:
# can also generate array with random values
np.random.sample((2, 3, 5))

array([[[0.94032881, 0.06736126, 0.03698863, 0.38850619, 0.27291836],
        [0.45111367, 0.99331682, 0.91598276, 0.24600779, 0.16752903],
        [0.31437809, 0.43213468, 0.49322228, 0.54620169, 0.52314632]],

       [[0.74606031, 0.91529667, 0.65671478, 0.48506986, 0.48963028],
        [0.86533758, 0.66964656, 0.75260259, 0.63632789, 0.2942819 ],
        [0.97251017, 0.60705604, 0.51372245, 0.84137036, 0.17673686]]])

In [ ]:
# generates array with random values (0-1)
np.random.rand(2, 3, 5)

array([[[0.52005959, 0.61863904, 0.76570508, 0.18282165, 0.13469097],
        [0.26133591, 0.36732386, 0.28330991, 0.51557461, 0.14649211],
        [0.18665177, 0.46080381, 0.60608664, 0.0107757 , 0.74458605]],

       [[0.80391503, 0.81182871, 0.21218225, 0.45427174, 0.66323079],
        [0.98802635, 0.12246037, 0.65680189, 0.90664144, 0.23579685],
        [0.85051803, 0.15412237, 0.32235058, 0.90971389, 0.21147423]]])

In [ ]:
# generates random integer within a given range
np.random.randint(low=10, high=25)

16

In [ ]:
# can also generate an array
np.random.randint(10, 25, (2, 3, 4))

array([[[18, 22, 11, 15],
        [21, 23, 15, 20],
        [22, 12, 23, 24]],

       [[15, 21, 20, 18],
        [16, 17, 14, 15],
        [22, 13, 18, 23]]])

In [ ]:
# also in numpy i can choose what tyoe of distribution i need
np.random.normal(5, 1, 10)
# first is expected value, second is dispersion and last one is size

array([5.88792418, 4.67423279, 5.19692626, 5.46863255, 4.76775009,
       6.54505408, 5.87227686, 5.42202568, 6.36993248, 5.02981696])

In [53]:
np.random.uniform(5, 10, 10)

array([9.17991979, 7.27666413, 9.47058836, 9.33774199, 7.31754222,
       8.74150716, 5.85861053, 9.82971292, 9.83874606, 8.46978461])