In [2]:
import numpy as np

In [3]:
a = np.array([[[1, 2, 3], [4, 10, 7]], [[101, 13, 28], [44, 5, 18]]])

In [4]:
a.shape, a

((2, 2, 3),
 array([[[  1,   2,   3],
         [  4,  10,   7]],
 
        [[101,  13,  28],
         [ 44,   5,  18]]]))

In [5]:
# the differnce between maximum and minimum values
np.ptp(a)

np.int64(100)

In [6]:
# this function is used when i need to scale values. For example if some values presented as hundreds and others as tens i need to make them somewhat comperrable
# using ptp i can divide element bu ptp value 
# i also can specifie axis

In [7]:
# axis=0 will go for each element through all matrices
# axis=1 will go vertically inside each matrix
# axis=2 will go horizontally inside each matrix
np.ptp(a, axis=0), np.ptp(a, axis=1), np.ptp(a, axis=2)

(array([[100,  11,  25],
        [ 40,   5,  11]]),
 array([[ 3,  8,  4],
        [57,  8, 10]]),
 array([[ 2,  6],
        [88, 39]]))

In [8]:
# this is function for percentile (item with 20th percentile means that 20% of values are lower/less then this item and 80% are bigger/greater)
# q is the percentile value im looking for
np.percentile(a, q=50, axis=0)
# sometimes percentile value is not present in array, so in interpolates and put number inbetween. This is why some results are float

array([[51. ,  7.5, 15.5],
       [24. ,  7.5, 12.5]])

In [9]:
a

array([[[  1,   2,   3],
        [  4,  10,   7]],

       [[101,  13,  28],
        [ 44,   5,  18]]])

In [10]:
# i can change interpolation method
# with this array it is not very clear, because i have only to values to choose from, so between 101 and 1 closest is 1
np.percentile(a, q=50, axis=0, method='closest_observation')

array([[1, 2, 3],
       [4, 5, 7]])

In [11]:
# there is same function, main difference is in points it calculates
# np.percentile is from 1 to 100 and np.quantile is from 0 to 1
np.quantile(a, q=0.5, axis=0, method='closest_observation')

array([[1, 2, 3],
       [4, 5, 7]])

In [12]:
# median, here i cant change interpolation method
np.median(a), np.median(a, axis=1)

(np.float64(8.5),
 array([[ 2.5,  6. ,  5. ],
        [72.5,  9. , 23. ]]))

In [13]:
# average
np.average(a), np.average(a, axis=2)

(np.float64(19.666666666666668),
 array([[ 2.        ,  7.        ],
        [47.33333333, 22.33333333]]))

In [14]:
a

array([[[  1,   2,   3],
        [  4,  10,   7]],

       [[101,  13,  28],
        [ 44,   5,  18]]])

In [15]:
# variation
np.var(a), np.var(a, axis=1)

(np.float64(748.0555555555553),
 array([[  2.25,  16.  ,   4.  ],
        [812.25,  16.  ,  25.  ]]))

In [16]:
# also can be used as method
a.var(), a.var(axis=1)

(np.float64(748.0555555555553),
 array([[  2.25,  16.  ,   4.  ],
        [812.25,  16.  ,  25.  ]]))

In [17]:
# standard deviation
np.std(a),np.std(a, axis=1)

(np.float64(27.350604299641265),
 array([[ 1.5,  4. ,  2. ],
        [28.5,  4. ,  5. ]]))

In [18]:
# also can be used as method
a.std(), a.std(axis=1)

(np.float64(27.350604299641265),
 array([[ 1.5,  4. ,  2. ],
        [28.5,  4. ,  5. ]]))

In [19]:
# correlation

In [20]:
x = np.random.rand(3, 3)
x

array([[0.87588031, 0.8208597 , 0.57628909],
       [0.40871386, 0.24109375, 0.99884659],
       [0.68889758, 0.66564621, 0.04676684]])

In [21]:
np.corrcoef(x, rowvar=False)

array([[ 1.        ,  0.98916048, -0.54257763],
       [ 0.98916048,  1.        , -0.66004154],
       [-0.54257763, -0.66004154,  1.        ]])

In [22]:
np.cov(x)

array([[ 0.02543282, -0.05881668,  0.05750262],
       [-0.05881668,  0.15842375, -0.14066709],
       [ 0.05750262, -0.14066709,  0.13264736]])