In [20]:
import numpy as np

In [21]:
# broadcasting is used when im working with arrays which have different dimensions
x = np.array([1, 2, 3])
a = 5

In [22]:
# numpy interprets 'a' as array [5, 5, 5] - it changes the size of smaller arrays to match bigger ones (with limitations ofc)
x * a

array([ 5, 10, 15])

In [23]:
x = np.ones(shape=(2, 3, 5, 1))
y = np.ones(shape=(2, 1, 5, 8))

c = x * y
c.shape # has a shape as the biggest array in equation (combined, to fit both)

(2, 3, 5, 8)

In [24]:
# does the same even if number of dimensions is different 
x1 = np.ones(shape=(3, 5, 1))
y1 = np.ones(shape=(2, 1, 5, 8))

z = x1 * y1
z.shape 

(2, 3, 5, 8)

In [25]:
# it works better with 1, because it's obvious how to interpret 1 - just make more. When it comes to 2, 3 etc numpy does not know what to make more
x2 = np.ones(shape=(3, 5, 1))
y2 = np.ones(shape=(2, 4, 5, 8))

#u = x2 * y2
#u.shape 

In [26]:
# there are multiple ways of changing size of array

In [27]:
a = np.ones((3, 5, 4, 1))
a.shape, a.ndim

((3, 5, 4, 1), 4)

In [28]:
# reshape() changes size by given parameters
# if 1 stands on the right or left of the array shape it means that it can be dropped without loosing information
a1 = a.reshape((3, 5, 4))
a1.shape

(3, 5, 4)

In [29]:
# reshape() only works if it is not changing any data
#a2 = a.reshape((3, 5, 4, 2))

In [30]:
# this works because i didnt change size - it was 60 and still is 60 after reshaping
a3 = a.reshape(3, 5, 2, 2)

In [31]:
a3.shape

(3, 5, 2, 2)

In [32]:
# if i want to reshape array, but dont know witch size to choose i can type -1 and numpy will find value
a3.reshape(3, 5, 4, -1).shape

(3, 5, 4, 1)

In [33]:
# this function can change size and data - it will repeat data if needed
np.resize(a, new_shape=(3, 5, 4, 2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
   

In [34]:
# it can be done in place, tho it will fill it by 0, not copy of data from array
b = np.ones((3, 4, 2, 1))
b.resize((3, 4, 2, 6))
b

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]])

In [35]:
# this is like a picture - colour 3, w - 500, h - 1000
a = np.ones((3, 500, 1000))

In [36]:
# so for example i need to import this image with specific format
# format 1*channel*1*w*1*h
# this function inserts new axis, so in my case it will be 0, 2, 4
b = np.expand_dims(a, axis=(0, 2, 4))
b.shape

(1, 3, 1, 500, 1, 1000)

In [37]:
ar = np.array([1, 2, 3])
ar

array([1, 2, 3])

In [38]:
# it looks like just adding new layers of []
np.expand_dims(ar, (0))

array([[1, 2, 3]])

In [39]:
# this is how i can reduce dimensions of the array
# works only with dimension size 1
b.shape

(1, 3, 1, 500, 1, 1000)

In [40]:
# by default will drop all dimensions with 1 size
b.squeeze().shape

(3, 500, 1000)

In [41]:
# i can specify what axies i need to drop
b.squeeze((0)).shape

(3, 1, 500, 1, 1000)

In [42]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [43]:
# this function adds values from left and right to the array
# pad_width first value how much to add on the left, second - on the right
np.pad(a, pad_width=(2, 3), constant_values=44)

array([44, 44,  1,  2,  3, 44, 44, 44])

In [44]:
# there is also mode argument - it defines what values the array are going to be filled with
np.pad(a, (2, 3), mode='median'), np.pad(a, (2, 3), 'edge')

(array([2, 2, 1, 2, 3, 2, 2, 2]), array([1, 1, 1, 2, 3, 3, 3, 3]))

In [45]:
# flattening arrays

In [46]:
b.shape # -> 1500000

(1, 3, 1, 500, 1, 1000)

In [47]:
# order is an argument for changing the behaviour of flattening - by row, column, etc 
np.ravel(b, order='C').shape

(1500000,)

In [48]:
b.flatten().shape

(1500000,)

In [49]:
b.reshape(-1).shape

(1500000,)

In [50]:
arr = np.array([[1,2,3], [4, 5,6]])

In [51]:
arr, arr.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [52]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [53]:
# here is how i can make basic python list from np.array
p_lst = arr.tolist()
type(p_lst), p_lst

(list, [[1, 2, 3], [4, 5, 6]])

In [54]:
# inserting into np.arrays, splitting np.arrays

In [55]:
a = np.arange(9)
b = np.array([[1, 2, 3], [4, 5, 6]])
a, b, b.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [56]:
# can split only into similar size arrays
# so if i put only one value - it is by equal sections 
np.split(a, indices_or_sections=3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [57]:
# if i put multiple values in list - it is by indexes
# this means - 3 first values, then from 3rd to 5th, and from 5th till the 15th (end)
np.split(a, [3, 5, 15])

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]), array([], dtype=int64)]

In [58]:
# this is how it works with more complex arrays
np.split(b, 2), np.split(b, 3, axis=1)

([array([[1, 2, 3]]), array([[4, 5, 6]])],
 [array([[1],
         [4]]),
  array([[2],
         [5]]),
  array([[3],
         [6]])])

In [59]:
# Inserting values

In [60]:
b ,b.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [61]:
# obj - indicates where to insert by index
# values - what to insert
# axis - on what axis to insert
np.insert(b, obj=1, values=404, axis=1)

array([[  1, 404,   2,   3],
       [  4, 404,   5,   6]])

In [62]:
# obj and values can read collections of values
# if im using both multiple obj and values each index corresponds to a specific value (in order)
np.insert(b, obj=(1, 2), values=(404, 6666), axis=1)

array([[   1,  404,    2, 6666,    3],
       [   4,  404,    5, 6666,    6]])

In [63]:
# but if i dont put any axies my n-dimensional array will become 1d
np.insert(b,(1,2) ,(404, 606))

array([  1, 404,   2, 606,   3,   4,   5,   6])

In [64]:
# i also can use append for arrays
# dimension of appending values must be the same as the dimension of array, in this case i have size (2, 3), so 2 
np.append(b, values=[[404], [606]], axis=1)

array([[  1,   2,   3, 404],
       [  4,   5,   6, 606]])

In [65]:
# this is how i can work with unique values in array
b1 = np.append(b, [[1, 2, 3]], axis=0)
b1 = np.append(b1, [[1], [1], [1]], axis=1)
b1

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [66]:
# 0 is vertically
# 1 is horizontally
np.unique(b1, axis=0), np.unique(b1, axis=1)

(array([[1, 2, 3, 1],
        [4, 5, 6, 1]]),
 array([[1, 1, 2, 3],
        [1, 4, 5, 6],
        [1, 1, 2, 3]]))

In [67]:
# return_index if True returns indexes of unique elements in array
np.unique(b1, axis=0, return_index=True)

(array([[1, 2, 3, 1],
        [4, 5, 6, 1]]),
 array([0, 1]))

In [68]:
# return_inverse if True returns indexes in order so we know to recreate initial array
# in this case i need to take 0 (first) element, then 1 (second) and again 0 (first)
np.unique(b1, axis=0, return_inverse=True)

(array([[1, 2, 3, 1],
        [4, 5, 6, 1]]),
 array([0, 1, 0]))

In [69]:
# return_counts if True returns how many times each element repeates
np.unique(b1, axis=0, return_counts=True)

(array([[1, 2, 3, 1],
        [4, 5, 6, 1]]),
 array([2, 1]))

In [ ]:
# here is how i can make a copy of array

In [72]:
b1

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [ ]:
# this function just repeats horizontally array by how many times i tell it to
np.tile(b1, (2))

array([[1, 2, 3, 1, 1, 2, 3, 1],
       [4, 5, 6, 1, 4, 5, 6, 1],
       [1, 2, 3, 1, 1, 2, 3, 1]])

In [78]:
# if i write like this it will repeat array vertically
np.tile(b1, (2, 1))

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1],
       [1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [ ]:
# if i type like this it will do both
# so the logic is like if given one number it is horizontally, if given two the first one if for
# vertical repeats and second one is for horizontal repeats
np.tile(b1, (3, 2))

array([[1, 2, 3, 1, 1, 2, 3, 1],
       [4, 5, 6, 1, 4, 5, 6, 1],
       [1, 2, 3, 1, 1, 2, 3, 1],
       [1, 2, 3, 1, 1, 2, 3, 1],
       [4, 5, 6, 1, 4, 5, 6, 1],
       [1, 2, 3, 1, 1, 2, 3, 1],
       [1, 2, 3, 1, 1, 2, 3, 1],
       [4, 5, 6, 1, 4, 5, 6, 1],
       [1, 2, 3, 1, 1, 2, 3, 1]])

In [ ]:
# this function will repeat every element and return flattened array if axis is not given
np.repeat(b1, 2)

array([1, 1, 2, 2, 3, 3, 1, 1, 4, 4, 5, 5, 6, 6, 1, 1, 1, 1, 2, 2, 3, 3,
       1, 1])

In [94]:
# i can specifie on witch axis to do so
# 0 - vertically
# 1 - horizontally
np.repeat(b1, 2, axis=0)

array([[1, 2, 3, 1],
       [1, 2, 3, 1],
       [4, 5, 6, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1],
       [1, 2, 3, 1]])

In [ ]:
# main difference in np.repeat and np.tile is that tile repeats array as a whole
# and repeat repeats each element one by one 
# so i can see in example above that each row repeats one by one 

In [ ]:
# 