In [1]:
import numpy as np

In [2]:
# broadcasting is used when im working with arrays which have different dimensions
x = np.array([1, 2, 3])
a = 5

In [3]:
# numpy interprets 'a' as array [5, 5, 5] - it changes the size of smaller arrays to match bigger ones (with limitations ofc)
x * a

array([ 5, 10, 15])

In [4]:
x = np.ones(shape=(2, 3, 5, 1))
y = np.ones(shape=(2, 1, 5, 8))

c = x * y
c.shape # has a shape as the biggest array in equation (combined, to fit both)

(2, 3, 5, 8)

In [5]:
# does the same even if number of dimensions is different 
x1 = np.ones(shape=(3, 5, 1))
y1 = np.ones(shape=(2, 1, 5, 8))

z = x1 * y1
z.shape 

(2, 3, 5, 8)

In [6]:
# it works better with 1, because it's obvious how to interpret 1 - just make more. When it comes to 2, 3 etc numpy does not know what to make more
x2 = np.ones(shape=(3, 5, 1))
y2 = np.ones(shape=(2, 4, 5, 8))

u = x2 * y2
u.shape 

ValueError: operands could not be broadcast together with shapes (3,5,1) (2,4,5,8) 

In [7]:
# there are multiple ways of changing size of array

In [8]:
a = np.ones((3, 5, 4, 1))
a.shape, a.ndim

((3, 5, 4, 1), 4)

In [9]:
# reshape() changes size by given parameters
# if 1 stands on the right or left of the array shape it means that it can be dropped without loosing information
a1 = a.reshape((3, 5, 4))
a1.shape

(3, 5, 4)

In [ ]:
# reshape() only works if it is not changing any data
a2 = a.reshape((3, 5, 4, 2))

ValueError: cannot reshape array of size 60 into shape (3,5,4,2)

In [ ]:
# this works because i didnt change size - it was 60 and still is 60 after reshaping
a3 = a.reshape(3, 5, 2, 2)

In [32]:
a3.shape

(3, 5, 2, 2)

In [ ]:
# if i want to reshape array, but dont know witch size to choose i can type -1 and numpy will find value
a3.reshape(3, 5, 4, -1).shape

(3, 5, 4, 1)

In [11]:
# this function can change size and data - it will repeat data if needed
np.resize(a, new_shape=(3, 5, 4, 2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
   

In [12]:
# it can be done in place, tho it will fill it by 0, not copy of data from array
b = np.ones((3, 4, 2, 1))
b.resize((3, 4, 2, 6))
b

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]])

In [13]:
# this is like a picture - colour 3, w - 500, h - 1000
a = np.ones((3, 500, 1000))

In [14]:
# so for example i need to import this image with specific format
# format 1*channel*1*w*1*h
# this function inserts new axis, so in my case it will be 0, 2, 4
b = np.expand_dims(a, axis=(0, 2, 4))
b.shape

(1, 3, 1, 500, 1, 1000)

In [15]:
ar = np.array([1, 2, 3])
ar

array([1, 2, 3])

In [16]:
# it looks like just adding new layers of []
np.expand_dims(ar, (0))

array([[1, 2, 3]])

In [17]:
# this is how i can reduce dimensions of the array
# works only with dimension size 1
b.shape

(1, 3, 1, 500, 1, 1000)

In [ ]:
# by default will drop all dimensions with 1 size
b.squeeze().shape

(3, 500, 1000)

In [ ]:
# i can specify what axies i need to drop
b.squeeze((0)).shape

(3, 1, 500, 1, 1000)

In [26]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
# this function adds values from left and right to the array
# pad_width first value how much to add on the left, second - on the right
np.pad(a, pad_width=(2, 3), constant_values=44)

array([44, 44,  1,  2,  3, 44, 44, 44])

In [31]:
# there is also mode argument - it defines what values the array are going to be filled with
np.pad(a, (2, 3), mode='median'), np.pad(a, (2, 3), 'edge')

(array([2, 2, 1, 2, 3, 2, 2, 2]), array([1, 1, 1, 2, 3, 3, 3, 3]))