In [2]:
import numpy as np

In [3]:
# broadcasting is used when im working with arrays which have different dimensions
x = np.array([1, 2, 3])
a = 5

In [4]:
# numpy interprets 'a' as array [5, 5, 5] - it changes the size of smaller arrays to match bigger ones (with limitations ofc)
x * a

array([ 5, 10, 15])

In [5]:
x = np.ones(shape=(2, 3, 5, 1))
y = np.ones(shape=(2, 1, 5, 8))

c = x * y
c.shape # has a shape as the biggest array in equation (combined, to fit both)

(2, 3, 5, 8)

In [6]:
# does the same even if number of dimensions is different 
x1 = np.ones(shape=(3, 5, 1))
y1 = np.ones(shape=(2, 1, 5, 8))

z = x1 * y1
z.shape 

(2, 3, 5, 8)

In [7]:
# it works better with 1, because it's obvious how to interpret 1 - just make more. When it comes to 2, 3 etc numpy does not know what to make more
x2 = np.ones(shape=(3, 5, 1))
y2 = np.ones(shape=(2, 4, 5, 8))

#u = x2 * y2
#u.shape 

In [8]:
# there are multiple ways of changing size of array

In [9]:
a = np.ones((3, 5, 4, 1))
a.shape, a.ndim

((3, 5, 4, 1), 4)

In [10]:
# reshape() changes size by given parameters
# if 1 stands on the right or left of the array shape it means that it can be dropped without loosing information
a1 = a.reshape((3, 5, 4))
a1.shape

(3, 5, 4)

In [11]:
# reshape() only works if it is not changing any data
#a2 = a.reshape((3, 5, 4, 2))

In [12]:
# this works because i didnt change size - it was 60 and still is 60 after reshaping
a3 = a.reshape(3, 5, 2, 2)

In [13]:
a3.shape

(3, 5, 2, 2)

In [14]:
# if i want to reshape array, but dont know witch size to choose i can type -1 and numpy will find value
a3.reshape(3, 5, 4, -1).shape

(3, 5, 4, 1)

In [15]:
# this function can change size and data - it will repeat data if needed
np.resize(a, new_shape=(3, 5, 4, 2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
   

In [16]:
# it can be done in place, tho it will fill it by 0, not copy of data from array
b = np.ones((3, 4, 2, 1))
b.resize((3, 4, 2, 6))
b

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]])

In [17]:
# this is like a picture - colour 3, w - 500, h - 1000
a = np.ones((3, 500, 1000))

In [18]:
# so for example i need to import this image with specific format
# format 1*channel*1*w*1*h
# this function inserts new axis, so in my case it will be 0, 2, 4
b = np.expand_dims(a, axis=(0, 2, 4))
b.shape

(1, 3, 1, 500, 1, 1000)

In [19]:
ar = np.array([1, 2, 3])
ar

array([1, 2, 3])

In [20]:
# it looks like just adding new layers of []
np.expand_dims(ar, (0))

array([[1, 2, 3]])

In [21]:
# this is how i can reduce dimensions of the array
# works only with dimension size 1
b.shape

(1, 3, 1, 500, 1, 1000)

In [22]:
# by default will drop all dimensions with 1 size
b.squeeze().shape

(3, 500, 1000)

In [23]:
# i can specify what axies i need to drop
b.squeeze((0)).shape

(3, 1, 500, 1, 1000)

In [24]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [25]:
# this function adds values from left and right to the array
# pad_width first value how much to add on the left, second - on the right
np.pad(a, pad_width=(2, 3), constant_values=44)

array([44, 44,  1,  2,  3, 44, 44, 44])

In [26]:
# there is also mode argument - it defines what values the array are going to be filled with
np.pad(a, (2, 3), mode='median'), np.pad(a, (2, 3), 'edge')

(array([2, 2, 1, 2, 3, 2, 2, 2]), array([1, 1, 1, 2, 3, 3, 3, 3]))

In [27]:
# flattening arrays

In [28]:
b.shape # -> 1500000

(1, 3, 1, 500, 1, 1000)

In [29]:
# order is an argument for changing the behaviour of flattening - by row, column, etc 
np.ravel(b, order='C').shape

(1500000,)

In [30]:
b.flatten().shape

(1500000,)

In [31]:
b.reshape(-1).shape

(1500000,)

In [32]:
arr = np.array([[1,2,3], [4, 5,6]])

In [33]:
arr, arr.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [34]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [35]:
# here is how i can make basic python list from np.array
p_lst = arr.tolist()
type(p_lst), p_lst

(list, [[1, 2, 3], [4, 5, 6]])

In [36]:
# inserting into np.arrays, splitting np.arrays

In [37]:
a = np.arange(9)
b = np.array([[1, 2, 3], [4, 5, 6]])
a, b, b.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [38]:
# can split only into similar size arrays
# so if i put only one value - it is by equal sections 
np.split(a, indices_or_sections=3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [39]:
# if i put multiple values in list - it is by indexes
# this means - 3 first values, then from 3rd to 5th, and from 5th till the 15th (end)
np.split(a, [3, 5, 15])

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]), array([], dtype=int64)]

In [40]:
# this is how it works with more complex arrays
np.split(b, 2), np.split(b, 3, axis=1)

([array([[1, 2, 3]]), array([[4, 5, 6]])],
 [array([[1],
         [4]]),
  array([[2],
         [5]]),
  array([[3],
         [6]])])

In [41]:
# Inserting values

In [42]:
b ,b.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [43]:
# obj - indicates where to insert by index
# values - what to insert
# axis - on what axis to insert
np.insert(b, obj=1, values=404, axis=1)

array([[  1, 404,   2,   3],
       [  4, 404,   5,   6]])

In [44]:
# obj and values can read collections of values
# if im using both multiple obj and values each index corresponds to a specific value (in order)
np.insert(b, obj=(1, 2), values=(404, 6666), axis=1)

array([[   1,  404,    2, 6666,    3],
       [   4,  404,    5, 6666,    6]])

In [45]:
# but if i dont put any axies my n-dimensional array will become 1d
np.insert(b,(1,2) ,(404, 606))

array([  1, 404,   2, 606,   3,   4,   5,   6])

In [46]:
# i also can use append for arrays
# dimension of appending values must be the same as the dimension of array, in this case i have size (2, 3), so 2 
np.append(b, values=[[404], [606]], axis=1)

array([[  1,   2,   3, 404],
       [  4,   5,   6, 606]])

In [47]:
# this is how i can work with unique values in array
b1 = np.append(b, [[1, 2, 3]], axis=0)
b1 = np.append(b1, [[1], [1], [1]], axis=1)
b1

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [48]:
# 0 is vertically
# 1 is horizontally
np.unique(b1, axis=0), np.unique(b1, axis=1)

(array([[1, 2, 3, 1],
        [4, 5, 6, 1]]),
 array([[1, 1, 2, 3],
        [1, 4, 5, 6],
        [1, 1, 2, 3]]))

In [49]:
# return_index if True returns indexes of unique elements in array
np.unique(b1, axis=0, return_index=True)

(array([[1, 2, 3, 1],
        [4, 5, 6, 1]]),
 array([0, 1]))

In [50]:
# return_inverse if True returns indexes in order so we know to recreate initial array
# in this case i need to take 0 (first) element, then 1 (second) and again 0 (first)
np.unique(b1, axis=0, return_inverse=True)

(array([[1, 2, 3, 1],
        [4, 5, 6, 1]]),
 array([0, 1, 0]))

In [51]:
# return_counts if True returns how many times each element repeates
np.unique(b1, axis=0, return_counts=True)

(array([[1, 2, 3, 1],
        [4, 5, 6, 1]]),
 array([2, 1]))

In [52]:
# here is how i can make a copy of array

In [53]:
b1

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [54]:
# this function just repeats horizontally array by how many times i tell it to
np.tile(b1, (2))

array([[1, 2, 3, 1, 1, 2, 3, 1],
       [4, 5, 6, 1, 4, 5, 6, 1],
       [1, 2, 3, 1, 1, 2, 3, 1]])

In [55]:
# if i write like this it will repeat array vertically
np.tile(b1, (2, 1))

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1],
       [1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [56]:
# if i type like this it will do both
# so the logic is like if given one number it is horizontally, if given two the first one if for
# vertical repeats and second one is for horizontal repeats
np.tile(b1, (3, 2))

array([[1, 2, 3, 1, 1, 2, 3, 1],
       [4, 5, 6, 1, 4, 5, 6, 1],
       [1, 2, 3, 1, 1, 2, 3, 1],
       [1, 2, 3, 1, 1, 2, 3, 1],
       [4, 5, 6, 1, 4, 5, 6, 1],
       [1, 2, 3, 1, 1, 2, 3, 1],
       [1, 2, 3, 1, 1, 2, 3, 1],
       [4, 5, 6, 1, 4, 5, 6, 1],
       [1, 2, 3, 1, 1, 2, 3, 1]])

In [57]:
# this function will repeat every element and return flattened array if axis is not given
np.repeat(b1, 2)

array([1, 1, 2, 2, 3, 3, 1, 1, 4, 4, 5, 5, 6, 6, 1, 1, 1, 1, 2, 2, 3, 3,
       1, 1])

In [58]:
# i can specifie on witch axis to do so
# 0 - vertically
# 1 - horizontally
np.repeat(b1, 2, axis=0)

array([[1, 2, 3, 1],
       [1, 2, 3, 1],
       [4, 5, 6, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1],
       [1, 2, 3, 1]])

In [59]:
# main difference in np.repeat and np.tile is that tile repeats array as a whole
# and repeat repeats each element one by one 
# so i can see in example above that each row repeats one by one 

In [60]:
# concatination for arrays

In [61]:
b = np.append(b, [[1], [1]], axis=1)

In [62]:
b, b1
b2 = b.copy()
b2

array([[1, 2, 3, 1],
       [4, 5, 6, 1]])

In [63]:
# to concatinate arrays they must be same dimensions on the axis i am concatinating them
# since b and b1 have different size on 1 axis (horisontally), i can only use axis=0
np.concatenate((b, b1), axis=0)

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [64]:
# another option is to use H-stack or V-Stack
# H-stack is horizontal
# V-stack is vertical
np.vstack((b, b1)), np.hstack((b, b2))
# there are lots of stacking functions

(array([[1, 2, 3, 1],
        [4, 5, 6, 1],
        [1, 2, 3, 1],
        [4, 5, 6, 1],
        [1, 2, 3, 1]]),
 array([[1, 2, 3, 1, 1, 2, 3, 1],
        [4, 5, 6, 1, 4, 5, 6, 1]]))

In [69]:
b1

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [ ]:
# this function multiplies all elements in array
b1.prod() # by default it just mult all elements in array

np.int64(4320)

In [ ]:
# i can add axis
b1.prod(axis=1), b1.prod(axis=0)

(array([  6, 120,   6]), array([ 4, 20, 54,  1]))

In [77]:
b4 = b1*1.5461
b3 = b1*1.5461
b4

array([[1.5461, 3.0922, 4.6383, 1.5461],
       [6.1844, 7.7305, 9.2766, 1.5461],
       [1.5461, 3.0922, 4.6383, 1.5461]])

In [ ]:
# this is how to round values in array
b4.round(2)

array([[1.55, 3.09, 4.64, 1.55],
       [6.18, 7.73, 9.28, 1.55],
       [1.55, 3.09, 4.64, 1.55]])

In [ ]:
# to sort array i can use this function
b4.sort() # it will do it in place
b4

array([[1.5461, 1.5461, 3.0922, 4.6383],
       [1.5461, 6.1844, 7.7305, 9.2766],
       [1.5461, 1.5461, 3.0922, 4.6383]])

In [ ]:
# also there is np.sort() if i dont want to sort inplace
np.sort(b3)

array([[1.5461, 1.5461, 3.0922, 4.6383],
       [1.5461, 6.1844, 7.7305, 9.2766],
       [1.5461, 1.5461, 3.0922, 4.6383]])

In [82]:
# np.sort() also supports axies
np.sort(b3, axis=0)

array([[1.5461, 3.0922, 4.6383, 1.5461],
       [1.5461, 3.0922, 4.6383, 1.5461],
       [6.1844, 7.7305, 9.2766, 1.5461]])

In [ ]:
# this function returns index if minimum or maximum values in array
np.argmin(b3), np.argmax(b3)

(np.int64(0), np.int64(6))

In [ ]:
# here is function to extract main diagonal from matrix
aaa = np.arange(9).reshape(3, 3)
aaa

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
np.diag(aaa)

array([0, 4, 8])

In [95]:
# i also can cycle thru diags with argument k
np.diag(aaa, k=2), np.diag(aaa, k=1), np.diag(aaa, k=-1), np.diag(aaa, k=-2)

(array([2]), array([1, 5]), array([3, 7]), array([6]))

In [ ]:
# filtering arrays 

In [99]:
o = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
o

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# to filter array i can use np.where()
np.where(o < 4)
# returns two arrays 
# first is indexes of rows where elements where found
# second one is indexes of columns of elements

(array([0, 0, 0]), array([0, 1, 2]))

In [101]:
np.where(o%2 == 1)

(array([0, 0, 1, 1]), array([0, 2, 0, 2]))

In [ ]:
# with this i can get values themselfs
o[np.where(o%2 == 1)]

array([1, 3, 5, 7])

In [ ]:
# if i want to use more then one condition
np.where((a%2==1) & (a>3))
#
o[np.where((a%2==1) & (a>3))] # this is like using 'and' in if statment
#
o[np.where((a%2==1) | (a>3))] # this is like using 'or' in if statment

array([1, 3, 4, 5, 6, 7, 8])

In [112]:
# i also can create if-else
# it reads like np.where(if a > 5, return a, else return -1)
np.where(a > 5, a, -1)

array([[-1, -1, -1, -1],
       [-1,  6,  7,  8]])